data_dir: 'data/move_to_corner'
env:
  name: MoveToCorner
  resolution: LoRes4
  view: A
expert:
  name: MoveToCornerExpert
train:
  n_iters: 10000
policy:
  name: MagicalPolicy
  lr: 1e-4
algorithm:
  name: BehaviorCloning
 

