name: 'move_to_corner_hard_bc'
data_dir: 'data/move_to_corner_hard_10k'
env:
  name: MoveToCorner
  resolution: LoResCHW4E
  train_cond: 'TestJitter'
  eval_cond: 'TestAllButDynamics'
expert:
  name: MoveToCornerExpert
train:
  n_iters: 10000
  log_every: 100
  batch_size: 5
  save_every_leap: 0.1
policy:
  name: MagicalPolicy
  lr: 0.0001
  image_feat_dim: 256 
  net_arch: [256]
algorithm:
  name: BehaviorCloning
device: 0 
