name: 'move_to_corner_hard_dvae'
data_dir: 'data/move_to_corner_hard_10k'
env:
  name: MoveToCorner
  resolution: LoResCHW4E
  train_cond: 'TestJitter'
  eval_cond: 'TestAllButDynamics'
train:
  n_iters: 100000
  log_every: 100
  batch_size: 32
  lr: 0.0001
device: 0 
